usbgadget: autostart: don't print error on repeated nv.usbgadget.autostart=1
nvvar_add results in two calls to dev_set_param:
 - once when the existing global variable is found and set
 - once more when setting the nv variable

This results in an annoying but ultimately harmless message on startup:

  ERROR: USB multi gadget already registered
  ERROR: failed to create nv variable usbgadget.autostart: Device or
  resource busy

Avoid this by ignoring usbgadget.autostart=1 after it succeeded once.

This issue should only affect $global.usbgadget.autostart, because all
other global variables are "simple" meaning that they have no setters
triggered.

Fixes: 5a5c5178e7dc ("usbgadget: autostart: support delayed usbgadget.autostart=1")
Signed-off-by: Ahmad Fatoum <a.fatoum@pengutronix.de>
Signed-off-by: Sascha Hauer <s.hauer@pengutronix.de>