kwboot: add missing header to fix musl build
Building kwboot for musl instead of glibc results in a couple of errors:

  error: unknown type name 'fd_set'
  error: storage size of 'tv' isn't known
    142 |         struct timeval tv;
  warning: implicit declaration of function 'FD_ZERO'
  warning: implicit declaration of function 'FD_SET'
  warning: implicit declaration of function 'select'
  warning: implicit declaration of function 'FD_ISSET'

POSIX specifies[1] that all these symbols shall be defined by <sys/select.h>,
so include this missing header.

[1]: https://pubs.opengroup.org/onlinepubs/009695399/basedefs/sys/select.h.html

Reported-by: Alexandre Belloni <alexandre.belloni@bootlin.com>
Link: https://lore.kernel.org/openembedded-core/Y91ObtiQCtnpGaRH@mail.local/
Signed-off-by: Ahmad Fatoum <a.fatoum@pengutronix.de>
Reviewed-by: Marco Felsch <m.felsch@pengutronix.de>
Link: https://lore.barebox.org/20230217070810.3353123-1-a.fatoum@pengutronix.de
Signed-off-by: Sascha Hauer <s.hauer@pengutronix.de>