clk: k3: pll: initialize success flag in ti_pll_wait_for_lock
When built with clang, we run into following warning (turned error with
CONFIG_WERROR):

  drivers/clk/k3/pll.c:100:14: error: variable 'success' is used uninitialized
  whenever 'for' loop exits because its condition is false [-Werror,-Wsometimes-uninitialized]

Initialize the variable to fix.

Fixes: 657d39593b2f ("clk: add K3 clk driver")
Signed-off-by: Ahmad Fatoum <a.fatoum@pengutronix.de>
Link: https://lore.barebox.org/20260831144434.1032533-1-a.fatoum@pengutronix.de
Signed-off-by: Sascha Hauer <s.hauer@pengutronix.de>