ARM: rockchip: Add missing LIBFDT dependency to ARCH_ROCKCHIP_ATF_PASS_FDT
arch/arm/mach-rockchip/atf.pbl.o: in function `rk3562_barebox_entry':
arch/arm/mach-rockchip/atf.c:159: undefined reference to `fdt_open_into'

Signed-off-by: Robin van der Gracht <robin@protonic.nl>
Link: https://lore.barebox.org/20260304131417.564470-1-robin.van.der.gracht@protonic.nl
Signed-off-by: Sascha Hauer <s.hauer@pengutronix.de>