Documentation: devicetree: mention when symbols are required in base DT
The barebox error message:

  ERROR: of_resolver: __symbols__ missing from base devicetree

can be a bit cryptic if unfamiliar with how overlays work internally.

Let's mention the error message in the documentation, so it turns up in
a search and add some extra information.

Signed-off-by: Ahmad Fatoum <a.fatoum@pengutronix.de>
Link: https://lore.barebox.org/20250526100627.3202658-1-a.fatoum@pengutronix.de
Signed-off-by: Sascha Hauer <s.hauer@pengutronix.de>