ARM: i.MX: bbu: fix compilation without CONFIG_BAREBOX_UPDATE
Fix
include/mach/imx/bbu.h:208:1: error: expected identifier or ‘(’ before ‘{’ token

Signed-off-by: Andreas Kemnade <andreas@kemnade.info>
Reviewed-by: Marco Felsch <m.felsch@pengutronix.de>
Fixes: 6e0cb133be ("ARM: i.MX: bbu: add FlexSPI update handler")
Link: https://lore.barebox.org/20230420195255.1153119-1-andreas@kemnade.info
Signed-off-by: Sascha Hauer <s.hauer@pengutronix.de>