ARM: i.MX8MM: fix phy-reset gpio
Drop the Barebox local property since the upstream/linux device-tree is
handling it now within the phy and we get an error:

   ERROR: gpiolib: _gpio_request: gpio-118 (ethernet-phy@0) status -16
   ERROR: miibus0: failed to request reset gpio for: ethernet-phy@0

Signed-off-by: Marco Felsch <m.felsch@pengutronix.de>
Link: https://lore.barebox.org/20220616140246.2191569-1-m.felsch@pengutronix.de
Signed-off-by: Sascha Hauer <s.hauer@pengutronix.de>