pinctrl: imx-iomux-v2: correct names in EXPORT_SYMBOL macros
The functions have been renamed, but this has not been reflected in the
EXPORT_SYMBOL macros. Do that now.

Fixes several errors like this:
drivers/pinctrl/imx-iomux-v2.c:61:15: error:
	'mxc_iomux_mode' undeclared here (not in a function)
 EXPORT_SYMBOL(mxc_iomux_mode);

Signed-off-by: Lucas Stach <l.stach@pengutronix.de>
Signed-off-by: Sascha Hauer <s.hauer@pengutronix.de>