ARM: at91: include linux/types.h in aic.h
The header uses u32 in the at91_aic_redir() prototype, but does not
include a header providing the type, so any C file including it
without pulling in linux/types.h first fails to compile:

  include/mach/at91/aic.h:7:40: error: unknown type name 'u32'

Fix it and make the header self-contained.

Fixes: 53d48be1757d ("ARM: at91: add necessary Advanced Interrupt Controller configuration")
Signed-off-by: Ahmad Fatoum <a.fatoum@pengutronix.de>
Link: https://lore.barebox.org/20260921153548.783906-1-a.fatoum@pengutronix.de
Signed-off-by: Sascha Hauer <s.hauer@pengutronix.de>