at91: add missing clkdev changes
This fixes the following compile errors
  arch/arm/mach-at91/at91sam9g45.c:185:3: error: 'ohci_clk' undeclared here (not in a function)
  arch/arm/mach-at91/at91sam9g45.c:186:3: error: 'tcb1_clk' undeclared here (not in a function)
  arch/arm/mach-at91/at91sam9g45_devices.c: In function 'at91_add_device_mci':
  arch/arm/mach-at91/at91sam9g45_devices.c:258:2: warning: implicit declaration of function 'at91_clock_associate'
    [...]
  arch/arm/mach-at91/built-in.o: In function `at91_add_device_mci':
  sam9_smc.c:(.text.at91_add_device_mci+0x1d0): undefined reference to `at91_clock_associate'

  arch/arm/mach-at91/at91sam9260_devices.c: In function 'at91_add_device_mci':
  arch/arm/mach-at91/at91sam9260_devices.c:251:2: warning: implicit declaration of function 'at91_clock_associate'

which were introduced in commit:
  "at91: swtich to clkdev" (ae19fe26cc230bc38238c2d66b8f464761286316)

Signed-off-by: Hubert Feurstein <h.feurstein@gmail.com>
Cc: Jean-Christophe PLAGNIOL-VILLARD <plagnioj@jcrosoft.com>
Signed-off-by: Sascha Hauer <s.hauer@pengutronix.de>