clk: rockchip: add RK3562 clock and reset driver support
Add clock and reset controller support for RK3562 SoC with PLL
configurations and clock trees for all power domains.

During boot, the following errors were seen:
    ERROR: rockchip_rk3036_pll_set_rate: Invalid rate : 983040000 for pll clk pll_hpll
    ERROR: clk: couldn't set hpll clk rate to 983040000 (-22), current rate: 1000000000

The driver has not been fully tested yet and requires further testing
and fixes. The current setup is kept as-is for now to avoid changing the
driver without proper testing. Its enough for booting for now,
especially the current rate is not far from this rate.

Co-developed-by: Ahmad Fatoum <a.fatoum@pengutronix.de>
Signed-off-by: Ahmad Fatoum <a.fatoum@pengutronix.de>
Signed-off-by: Sohaib Mohamed <sohaib.amhmd@gmail.com>
Link: https://lore.barebox.org/20260130-barebox-kickpi-v2-2-d27cf94a39b6@gmail.com
Signed-off-by: Sascha Hauer <s.hauer@pengutronix.de>