globalvar: Add missing empty prototype for globalvar_set()
common/fastboot.c: In function 'cb_boot':
common/fastboot.c:396:2: error: implicit declaration of function 'globalvar_set'
globalvar_set("bootm.image", "");

Signed-off-by: Alexander Shiyan <eagle.alexander923@gmail.com>
Link: https://lore.barebox.org/20220601060226.3756-5-eagle.alexander923@gmail.com
Signed-off-by: Sascha Hauer <s.hauer@pengutronix.de>