EFI: add missing include
Otherwise building produces these warnings:
[...]
arch/efi/efi/efi-image.c:48:2: warning: implicit declaration of function 'read_file' [-Wimplicit-function-declaration]
arch/efi/efi/efi-image.c:48:6: warning: assignment makes pointer from integer without a cast [enabled by default]
[...]

And bootm fails for x86_64. The implicit declaration has an int as return
value, so half of the returned address is lost.

Signed-off-by: Michael Olbrich <m.olbrich@pengutronix.de>
Signed-off-by: Sascha Hauer <s.hauer@pengutronix.de>