scripts: socfpga_import_preloader: Use SDK-supplied Python
Change `generate_spl()` to use the `python` bundled with the SDK (SoC
EDS) instead of using `python2.7`.  In version 20.1 of SoC EDS, the
`iswgen.py` script was updated to work with Python 3.8 and no longer
works with Python 2.7, leading to an error similar to this when
generating the SPL:

```
Generating file: /tmp/tmp.0xSiyYqAU2//sdram//sdram_config.h...
Traceback (most recent call last):
  File "/opt/intelFPGA/20.1/embedded/ip/altera/preloader/scripts/iswgen.py", line 63, in <module>
    hps = hps.HPSGrokker(inputDir, outputDir)
  File "/opt/intelFPGA/20.1/embedded/ip/altera/preloader/scripts/hps.py", line 54, in __init__
    self.createFilesFromHPS()
  File "/opt/intelFPGA/20.1/embedded/ip/altera/preloader/scripts/hps.py", line 546, in createFilesFromHPS
    self.handleHPSPeripheralsNode(childNode)
  File "/opt/intelFPGA/20.1/embedded/ip/altera/preloader/scripts/hps.py", line 413, in handleHPSPeripheralsNode
    self.pinmuxHeaderBuffer.write("#define " + name + ' ' + '(' + str(used) + ')' + '\n')
TypeError: unicode argument expected, got 'str'
```

Signed-off-by: Ian Abbott <abbotti@mev.co.uk>
Link: https://lore.barebox.org/20230615123020.25927-1-abbotti@mev.co.uk
Signed-off-by: Sascha Hauer <s.hauer@pengutronix.de>