Revert "ARM: k3: define debug_ll_write_reg only on CONFIG_DEBUG_AM62X_UART=y"
This patch breaks compilation of beagleplay in multi_v8_defconfig:

arch/arm/boards/beagleplay/lowlevel.c:44:30: error:  debug_ll_ns16550_putc' undeclared (first use in
this function)
   44 |         pbl_set_putc((void *)debug_ll_ns16550_putc, (void *)AM62X_UART_UART0_BASE);

debug_ll_ns16550_putc() shoudn't be used as pbl putc function directly.
This should be fixed, but it is no material for master, so revert for
now.

This reverts commit 6b749354d11a475f54c51aa76f82e224b9b59ef3.