ARM: dts: stm32mp: stm32mp135-dk: disable button on PA13
After update to the v7.0-rc1 device trees, boot up on the board
reports following error:

  ERROR: gpiolib: _gpio_request: gpio-13 (led-red) status -16

This is caused by the combination of following two upstream kernel commits:

57012d79fefd ("ARM: dts: stm32: add UserPA13 button on stm32mp135f-dk")
31f0d9a486a8 ("ARM: dts: stm32: Add red LED for stm32mp135f-dk board")

Both reference the same &gpioa 13. Linux didn't seem to mind, but
barebox fails the LED driver probe, because the GPIO had already been
requested.

Assuming it is correct that they share the same GPIO physically,
Blinking the LED would register a button press, so it sounds not so
useful to have both enabled by default.

Thus disable the button in barebox.

This has been reported upstream at [1].

[1]: https://lore.kernel.org/all/382d28eb-557c-4cae-898c-8ed5c8cd7843@pengutronix.de/

Fixes: fe223ba39321 ("dts: update to v7.0-rc1")
Signed-off-by: Ahmad Fatoum <a.fatoum@pengutronix.de>
Link: https://lore.barebox.org/20260417122004.2030708-1-a.fatoum@pengutronix.de
Signed-off-by: Sascha Hauer <s.hauer@pengutronix.de>
(cherry picked from commit ce99330b64f35b52b05b384b98ae54c9811fedd9)
Signed-off-by: Ahmad Fatoum <a.fatoum@pengutronix.de>