ARM: nitrogen6x: remove conflicting upstream SPI NOR partitions
Since kernel commit 44eac6ef3779 ("ARM: dts: imx6qdl-nitrogen6x: Add SPI
NOR partitions"), included in barebox commit a9c5f6b9ec88 ("dts: update
to v4.16-rc1"), the upstream device tree contains partition definitions
that conflict with preexisting barebox partitions:

  ERROR: m25p0.env: New partition m25p0.env conflicts with m25p0.barebox
  ERROR: m25p0.splash: New partition m25p0.splash conflicts with m25p0.barebox

Remove them so we can add the larger barebox and barebox-environment
partitions that are used since commit 3fb70de496b3 ("ARM: i.MX: increase
barebox partition sizes").

Signed-off-by: Philipp Zabel <p.zabel@pengutronix.de>
Signed-off-by: Sascha Hauer <s.hauer@pengutronix.de>