common:environment: fix mode requirement
Issue:
Compiling on Ubuntu 8.10 Fails:
inlined from 'envfs_save' at scripts/../common/environment.c:135:
/usr/include/bits/fcntl2.h:51: error: call to '_open_missing_mod'
declared with attribute error: open with O_CREAT in second argument
needs 3 arguments

Usage: open(filename, O_WRONLY | O_CREAT)

Fix:
When using open with O_CREAT, it requires
mode to be defined.

Signed-off-by: Nishanth Menon <nm@ti.com>