pbl: console: fix undefined reference to vprintf()
panic() now uses vprintf() which is not available without
CONFIG_PBL_CONSOLE. Move the declaration to the right ifdeffery
which already handles that case.

Fixes: 33e3bc4782 ("pbl: fix panic() message printing")
Link: https://lore.barebox.org/20260304104904.1205995-1-s.hauer@pengutronix.de
Signed-off-by: Sascha Hauer <s.hauer@pengutronix.de>