mmc: add MCI_SDHCI dependency to Arasan driver
The Arasan driver depends on the SDHCI driver, without it we
will see undefined references while linking arasan-sdhci.c:283: undefined
reference to `sdhci_set_cmd_xfer_mode' arasan-sdhci.c:299: undefined
reference to `sdhci_read_response' arasan-sdhci.c:303: undefined reference to
`sdhci_transfer_data'

Signed-off-by: Michael Graichen <michael.graichen@hotmail.com>
Signed-off-by: Sascha Hauer <s.hauer@pengutronix.de>