ARM: k3: move am62x specific bits out of common file
k3_boot_is_emmc() is called from common.c, but is really am62x specific
and only compiled in when am62x support is enabled. With this compiling
for am62lx only fails with an undefined reference to k3_boot_is_emmc().

Move the am62x specific files out of common.c: Move the initcall to
am62x.c and call omap_env_init() (renamed to k3_env_init()) from there
after checking the prerequisites. Also rename k3_boot_is_emmc() to
am62x_boot_is_emmc().

Link: https://lore.barebox.org/20250910061824.2765659-1-s.hauer@pengutronix.de
Signed-off-by: Sascha Hauer <s.hauer@pengutronix.de>