[sandbox] HACK: add variable _SDA_BASE_ to main, to please linker
This patch is a _CRUDE_HACK_ the linker complains about the missing
symbol _SDA_BASE_ on powerpc, so git it to him to please him and
finally link the sandbx.

LD      uboot
/usr/lib/gcc/powerpc-linux-gnu/4.2.3/../../../../lib/crt1.o:(.rodata+0x0): undefined reference to `_SDA_BASE_'

Signed-off-by: Marc Kleine-Budde <mkl@pengutronix.de>