fastboot: implement dummy has-slot:partition variables
Now that we enforce variables to be available, flashing can result in
following error message:

  ERROR: fastboot: no such variable: has-slot:rootfs-eMMC

Report the default no value to suppress this.

Fixes: dd377c937f8b ("common: fastboot: send FAIL if variable does not exist")
Signed-off-by: Ahmad Fatoum <a.fatoum@pengutronix.de>
Link: https://lore.barebox.org/20250820101702.1946026-1-a.fatoum@pengutronix.de
Signed-off-by: Sascha Hauer <s.hauer@pengutronix.de>