mfd: rn5t568: add priority to reset_source_set_device()
30322f4b565 ("reset_source: give reset_source_set_device a priority
parameter") introduced a reset source priority parameter, but forgot
applying a priority the Ricoh RN5T568 PMIC driver's
reset_source_set_device() call.

So apply the default priority 200 here, too.

Fixes this build error:

  drivers/mfd/rn5t568.c: In function 'rn5t568_reset_reason_detect':
  drivers/mfd/rn5t568.c:82:9: error: too few arguments to function 'reset_source_set_device'
     82 |         reset_source_set_device(dev, type);
        |         ^~~~~~~~~~~~~~~~~~~~~~~
  In file included from drivers/mfd/rn5t568.c:17:
  include/reset_source.h:31:6: note: declared here
     31 | void reset_source_set_device(struct device *dev, enum reset_src_type st,
        |      ^~~~~~~~~~~~~~~~~~~~~~~

Fixes: 30322f4b565 ("reset_source: give reset_source_set_device a priority parameter")
Signed-off-by: Bastian Krause <bst@pengutronix.de>
Reviewed-by: Ahmad Fatoum <a.fatoum@pengutronix.de>
Link: https://lore.kernel.org/r/20250303143144.2953662-1-bst@pengutronix.de
Signed-off-by: Sascha Hauer <s.hauer@pengutronix.de>