fs: efivarfs: initialize dummy data written on variable creation
Building with clang reports:

  error: variable 'dummydata' is uninitialized when passed as a
    const pointer argument here [-Werror,-Wuninitialized-const-pointer]

Fix this by initializing the variable.

Fixes: 46b5a6d6527f ("fs: efivars: implement write support")
Signed-off-by: Ahmad Fatoum <a.fatoum@pengutronix.de>
Link: https://lore.barebox.org/20260831132456.730833-3-a.fatoum@pengutronix.de
Signed-off-by: Sascha Hauer <s.hauer@pengutronix.de>