net: workaround NICs and MDIO busses sharing same OF node
v2024.04.0 broke Ethernet on the Skov IMX6 board:

  ERROR: KSZ8873 MDIO mdio1-dev00: can't find ethernet master device

The board has an Ethernet switch controlled via a bitbanged
MDIO bus and the MDIO bus of the Ethernet device is unused.

The FEC node has no mdio subnode, just a fixed-link.

Starting with commit ac855ffe5730 ("net: phy: fix miibus parent
device of_node not matching phy node"), MDIO busses will get assigned
the device tree node of their parent if none was configured.
This means we have two devices competing for the same device tree node:

  barebox@Skov IMX6:/ devinfo 2188000.ethernet@2188000.of
  [...]
  Device node: /soc/bus@2100000/ethernet@2188000 (populated by miibus0)

This has the effect that calling of_device_ensure_probed on the device
tree fails with -EPROBE_DEFER because miibus0 has no driver bound and
the network device itself is ignored.

We probably want to rethink allowing multiple devices to share the same
device tree node, especially for network drivers. But as long this is
the case, fix the regression by always walking the list of registered
device tree nodes.

Fixes: ac855ffe5730 ("net: phy: fix miibus parent device of_node not matching phy node")
Signed-off-by: Ahmad Fatoum <a.fatoum@pengutronix.de>
Link: https://lore.barebox.org/20240502070328.2218748-1-a.fatoum@pengutronix.de
Signed-off-by: Sascha Hauer <s.hauer@pengutronix.de>