ARM: boards: skov-imx6: fix device tree path of state node
The reference broke in commit [1] and led to the following error message during
boot while fixing up the kernel devicetree:

  Loading ARM Linux zImage '/mnt/nand0.firmware.ubi.system0//boot/zImage'
  Loading devicetree from '/mnt/nand0.firmware.ubi.system0//boot/imx6dl-skov-revc-lt2.dtb'
  ERROR: skov-imx6 machine: Node /state/ethaddr/eth2 defining the state variable not found.

[1] c00df6a4b552 ("ARM: dts: Fix dtc warnings in state nodes")

Link: https://lore.barebox.org/20260630124732.709291-1-u.oelmann@pengutronix.de
Signed-off-by: Sascha Hauer <s.hauer@pengutronix.de>