efi: add missing Kconfig selects
Building EFI code without block device and partition support enabled
will fail with:

| drivers/built-in.o: In function `efi_bio_probe':
| (.text+0x125d): undefined reference to `blockdevice_register'
| drivers/built-in.o: In function `efi_bio_probe':
| (.text+0x126c): undefined reference to `parse_partition_table'
| Makefile:766: recipe for target 'barebox' failed

Thus always select BLOCK and PARTITION_DISK when enabling EFI_BOOTUP.

Signed-off-by: Enrico Jorns <ejo@pengutronix.de>
Signed-off-by: Sascha Hauer <s.hauer@pengutronix.de>