i2c: Fix barebox crash when 'count' is not set for i2c_read command
Running i2c_read without the 'count' setting causes an error and reboots.

barebox@Phytec phyCORE-i.MX27:/ i2c_read -b 1 -a 0x4a -r 0x00
ERROR: out of memory
no stack data available

Signed-off-by: Sascha Hauer <s.hauer@pengutronix.de>