MIPS: fix PCI quirk infrastructure build
The commit fc2c618c2038 ("pci: add quirk infrastructure")
adds necessary ld-script changes only for ARM architecture.
As a result, qemu-malta build fails:

     LD      barebox
    drivers/built-in.o: In function `pci_fixup_device':
    (.text.pci_fixup_device+0x30): undefined reference to `__end_pci_fixups_enable'
    (.text.pci_fixup_device+0x38): undefined reference to `__end_pci_fixups_enable'
    (.text.pci_fixup_device+0x34): undefined reference to `__start_pci_fixups_enable'
    (.text.pci_fixup_device+0x3c): undefined reference to `__start_pci_fixups_enable'
    (.text.pci_fixup_device+0x70): undefined reference to `__end_pci_fixups_header'
    (.text.pci_fixup_device+0x78): undefined reference to `__end_pci_fixups_header'
    (.text.pci_fixup_device+0x74): undefined reference to `__start_pci_fixups_header'
    (.text.pci_fixup_device+0x80): undefined reference to `__start_pci_fixups_header'
    (.text.pci_fixup_device+0x2c): undefined reference to `__end_pci_fixups_early'
    (.text.pci_fixup_device+0x88): undefined reference to `__end_pci_fixups_early'
    (.text.pci_fixup_device+0x84): undefined reference to `__start_pci_fixups_early'
    (.text.pci_fixup_device+0x90): undefined reference to `__start_pci_fixups_early'
    make: *** [Makefile:767: barebox] Error 1

Signed-off-by: Antony Pavlov <antonynpavlov@gmail.com>
Signed-off-by: Sascha Hauer <s.hauer@pengutronix.de>