clk: fractional-divider: fix build with CONFIG_MODULES
Fixes:
error: 'clk_register_fractional_divider' undeclared here

introduced with commit 22a0c31c9265 (CLK: Add fractional
divider clock support from Linux kernel)

Signed-off-by: Lucas Stach <l.stach@pengutronix.de>
Signed-off-by: Sascha Hauer <s.hauer@pengutronix.de>