habv4: ignore engine failure due to RNG self-test in
boot ROM

Few i.MX chips which have HAB 4.2.3 or beyond, have oberserved
following warning message generated by HAB due to incorrect
implementation of RNG self-test in boot ROM:

	HABv4: Status: Operation completed with warning (0x69)
	HABv4: Config: Non-secure IC (0xf0)
	HABv4: State: Non-secure state (0x66)
	ERROR: HABv4: -------- HAB Event 0 --------
	ERROR: HABv4: event data:
	ERROR: HABv4:  db 00 24 42  69 30 e1 1d
	ERROR: HABv4:  00 08 00 02  40 00 36 06
	ERROR: HABv4:  55 55 00 03  00 00 00 00
	ERROR: HABv4:  00 00 00 00  00 00 00 00
	ERROR: HABv4:  00 00 00 01
	ERROR: HABv4: Status: Operation completed with warning (0x69)
	ERROR: HABv4: Reason: Engine failure (0x30)
	ERROR: HABv4: Context: Event logged in hab_rvt.entry() (0xe1)
	ERROR: HABv4: Engine: CAAM (0x1d)

On these chips it is recommended to run the software self-test
in order to discover any other failure in addition to the
false positivie above.

This patch filters out the event and not show it as suggested in [1].

[1]
https://lore.barebox.org/barebox/ba1febb9b457f5876959f093f866b680e266f987.camel@pengutronix.de/

Suggested-by: Rouven Czerwinski <r.czerwinski@pengutronix.de>
Signed-off-by: Stefano Manni <stefano.manni@gmail.com>
Link: https://lore.barebox.org/9bf8686f882714867ac2dc864c8e5539ad06400b.camel@gmail.com
Signed-off-by: Sascha Hauer <s.hauer@pengutronix.de>