video: backlight-pwm: depend on GPIOLIB
The PWM backlight driver does not only control PWMs but also GPIOs.

Fixes:
In file included from include/gpio.h:4:0,
                 from drivers/video/backlight-pwm.c:27:
arch/arm/include/asm/gpio.h:5:23: fatal error: mach/gpio.h: No such file or directory

Signed-off-by: Lucas Stach <l.stach@pengutronix.de>
Signed-off-by: Sascha Hauer <s.hauer@pengutronix.de>