cmd: CMD_UBI depends on UBI
When ubi is deselected the ubi commands are still build and compiling fails
due dependences.

commands/built-in.o: In function `do_ubiattach':
commands/ubi.c:75: undefined reference to `ubi_attach_mtd_dev'

Signed-off-by: Teresa Gámez <t.gamez@phytec.de>
Signed-off-by: Sascha Hauer <s.hauer@pengutronix.de>