include: ocotp.h: add missing include
Otherwise GCC complains:

  <PATH>/barebox-2026.08.0/include/mach/imx/ocotp.h: In function 'imx_ocotp_read_uid':
  <PATH>/barebox-2026.08.0/include/mach/imx/ocotp.h:47:16: error: implicit declaration of function 'readl' [-Werror=implicit-function-declaration]
     47 |         uid  = readl(ocotp + OCOTP_UID_H);
        |                ^~~~~

Signed-off-by: Ulrich Ölmann <u.oelmann@pengutronix.de>
Link: https://lore.barebox.org/20260918093908.477071-1-u.oelmann@pengutronix.de
Signed-off-by: Sascha Hauer <s.hauer@pengutronix.de>