remoteproc: stm32: fix breakage after DT sync with upstream
Once more, a device tree sync with Linux breaks a barebox driver.

This time, the STM32 remoteproc driver ported from Linux was broken by
the upstream stm32mp151.dtsi removing the st,syscfg-tz property.

This property is only needed for the SiP secure monitor call case,
but was so far always specified and the driver required its presence,
even if it went unused.

The Linux driver has since removed this hard requirement and added a new
third way to do co-processor reset: Besides direct access to hardware
and Silicon Provider specific secure monitor call, there's also support
for doing it over SCMI now.

Sync that part with the Linux driver to fix following boot-time error
message:

  ERROR: stm32-rproc 10000000.m4@10000000.of: failed to get tz syscfg

Reported-by: Robert Schwebel <rsc@pengutronix.de>
Signed-off-by: Ahmad Fatoum <a.fatoum@pengutronix.de>
Link: https://lore.barebox.org/20231020133744.555063-2-a.fatoum@pengutronix.de
Signed-off-by: Sascha Hauer <s.hauer@pengutronix.de>