spi: stm32: avoid enabling SPI in setup to allow register configuration
The stm32_spi_setup function configures the STM32 SPI engine by setting
the SPI mode and speed. However, enabling the SPI peripheral during this
process blocks all changes to configuration registers, causing the
configuration writes to be ignored.

Remove stm32_spi_enable calls from stm32_spi_setup to ensure proper
configuration of the SPI registers before enabling the peripheral.

This fix addresses the following error on some platforms with an SJA1105
switch attached over SPI to an STM32MP151 SoC:
ERROR: sja1105 switch@00: Device tree specifies chip 2919236366/39557
       but found 3607101831/0, please fix it!
ERROR: sja1105 switch@00: Device ID check failed: -19

Signed-off-by: David Jander <david@protonic.nl>
Signed-off-by: Oleksij Rempel <o.rempel@pengutronix.de>
Link: https://lore.barebox.org/20240529100838.551840-1-o.rempel@pengutronix.de
Signed-off-by: Sascha Hauer <s.hauer@pengutronix.de>