of: partition: do not try to translate offset as OF address
of_platform_populate will eventually call of_platform_device_create,
which will print out errors for partitions with a compatible, because
of_translate_address chokes on the partitions container node as it's
not a valid platform (child) device:

  ERROR: prom_parse: Bad cell count for /soc/bus@5c007000/i2c@5c002000/eeprom@50/partitions

The correct fix would be not to use a platform bus here, but until we
add an alternative bus or switch to mtd_notifier as in Linux, just
create the platform device without the address translation parts.

Signed-off-by: Ahmad Fatoum <a.fatoum@pengutronix.de>
Link: https://lore.barebox.org/20250528150322.611761-1-a.fatoum@pengutronix.de
Signed-off-by: Sascha Hauer <s.hauer@pengutronix.de>